"""
Email summarizer module using Claude AI API.
"""
from anthropic import Anthropic
from typing import List, Dict
import os


class EmailSummarizer:
    def __init__(self, api_key: str):
        """
        Initialize the email summarizer with Claude API.

        Args:
            api_key: Anthropic API key
        """
        self.client = Anthropic(api_key=api_key)

    def create_summary(self, emails: List[Dict]) -> str:
        """
        Create an AI-powered summary of emails.

        Args:
            emails: List of email dictionaries with subject, sender, date, and body

        Returns:
            Summary string in HTML format
        """
        if not emails:
            return "<p>No new emails in the last 24 hours.</p>"

        # Prepare email content for Claude
        email_content = self._format_emails_for_ai(emails)

        # Create the prompt for Claude
        prompt = f"""You are an email assistant. Please analyze the following {len(emails)} emails received in the last 24 hours and create a concise, well-organized summary.

The summary should:
1. Highlight the most important emails first
2. Group similar emails together (e.g., newsletters, work emails, personal emails)
3. For each important email, include: sender, subject, and a brief summary of the content
4. Identify any emails that require urgent attention or action
5. Keep the overall summary concise but informative

Format the output as clean HTML that can be included in an email body. Use appropriate HTML tags like <h2>, <h3>, <p>, <ul>, <li>, <strong>, etc.

Here are the emails:

{email_content}

Please provide the summary:"""

        try:
            # Call Claude API
            message = self.client.messages.create(
                model="claude-3-5-sonnet-20241022",
                max_tokens=2000,
                temperature=0.3,
                messages=[
                    {"role": "user", "content": prompt}
                ]
            )

            summary = message.content[0].text

            # Add header with email count
            full_summary = f"""
<div style="font-family: Arial, sans-serif; max-width: 800px; margin: 0 auto;">
    <h1 style="color: #2c3e50; border-bottom: 2px solid #3498db; padding-bottom: 10px;">
        Daily Email Summary
    </h1>
    <p style="color: #7f8c8d; font-size: 14px;">
        Summary of {len(emails)} emails received in the last 24 hours
    </p>

    {summary}

    <hr style="margin-top: 30px; border: none; border-top: 1px solid #ecf0f1;">
    <p style="color: #95a5a6; font-size: 12px; text-align: center;">
        This summary was automatically generated by your Email Reader assistant.
    </p>
</div>
"""
            return full_summary

        except Exception as e:
            print(f"Error creating summary with Claude API: {e}")
            # Fallback to simple summary
            return self._create_simple_summary(emails)

    def _format_emails_for_ai(self, emails: List[Dict]) -> str:
        """
        Format emails for AI processing.

        Args:
            emails: List of email dictionaries

        Returns:
            Formatted string of emails
        """
        formatted = []

        for i, email_data in enumerate(emails, 1):
            formatted.append(f"""
Email #{i}:
From: {email_data['sender']}
Subject: {email_data['subject']}
Date: {email_data['date'].strftime('%Y-%m-%d %H:%M:%S')}
Content Preview: {email_data['body'][:300]}...
---
""")

        return "\n".join(formatted)

    def _create_simple_summary(self, emails: List[Dict]) -> str:
        """
        Create a simple fallback summary without AI.

        Args:
            emails: List of email dictionaries

        Returns:
            Simple HTML summary
        """
        html = f"""
<div style="font-family: Arial, sans-serif; max-width: 800px; margin: 0 auto;">
    <h1 style="color: #2c3e50;">Daily Email Summary</h1>
    <p>You received {len(emails)} emails in the last 24 hours:</p>
    <ul>
"""

        for email_data in emails:
            html += f"""
        <li>
            <strong>{email_data['subject']}</strong><br>
            From: {email_data['sender']}<br>
            Date: {email_data['date'].strftime('%Y-%m-%d %H:%M:%S')}
        </li>
"""

        html += """
    </ul>
</div>
"""
        return html
